{
    "chainId": 1,
    "event_cha": [
        {
            "chainId": "1",
            "chaName": "3월 1차 이벤트",
            "startDate": "2020-03-01",
            "endDate": "2020-03-15",
            "isTab": "0",
            "regDate": "2018-02-12 15:11:41",
            "showDate": "2018-05-30",
            "cha": "1",
            "imgcheck": "0",
            "chaName_jp": "3月1次 イベント",
            "chaName_th": "โปรโมชั่นครึ่งแรกของเดือนกุมภาพันธ์",
            "chaName_gd": "3月上半月活动",
            "chaName_eng": "March 1st",
            "chaName_vn": "Khuyến mãi tháng 1 lần 1"
        }
    ],
    "chaId": "1",
    "groups": [
        {
            "id": "374",
            "chainId": "1",
            "middleId": null,
            "groupName": "화/수/목 EVENT",
            "groupSubName": "[화/수/목 EVENT] 화/수/목요일 방문시 적용!",
            "dayOfTheWeek": "234",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "0",
            "regDate": "2019-01-28 10:31:59",
            "selected": "1",
            "selected_list": "0",
            "startDate_list": null,
            "endDate_list": null,
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "2",
            "orderby_0": "0",
            "print_orderby_1": "0",
            "print_orderby_2": "0",
            "createAdminId": "jyh6764",
            "lastUpdateAdminId": null,
            "groupName_eng": "Tue/Wed/Thu Events",
            "groupSubName_eng": "",
            "groupName_jp": "火/水/木曜イベント",
            "groupSubName_jp": "",
            "groupName_th": "โปรวันอังคาร/พุธ/พฤหัส",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,eng,jp,th,vn",
            "groupName_vn": "Khuyến mãi thứ ba/ thứ tư/ thứ năm",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "2819",
                    "groupId": "374",
                    "middleId": "54",
                    "originalPrice": "80000",
                    "discountedPrice": "45000",
                    "itemName": "턱필러 0.5cc + 자갈턱보톡스",
                    "itemSubName": "[화/수/목 이벤트]<br>턱필러(에피티크) 0.5cc <br>+ 자갈턱보톡스",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "あごフィラー（アティエル1㏄）＋梅干しジワボトックス",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>細くて堂々なVラインあごライン！",
                    "itemName_th": "ฟิลเลอร์คาง  0.5 cc + โบท็อกซ์ปลายคาง",
                    "itemSubName_th": " [โปรโมชั่นวันอังคาร/พุธ/พฤหัส]<br> ฟิลเลอร์ยี่ห้อ  EPTQ จากเกาหลีใต้<br>สามารถชำระเพิ่มอีก 33,000 วอนหากต้องการเพิ่มอีก 0.5cc ",
                    "itemName_vn": "Filler cằm(Atiere 1cc) +  Botox cằm ",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br>Khiến cơ bắp trở nên thon thả!",
                    "cha": "374",
                    "cha_2": "374",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "얼굴필러"
                },
                {
                    "id": "546",
                    "groupId": "374",
                    "middleId": "48",
                    "originalPrice": "110000",
                    "discountedPrice": "59000",
                    "itemName": "코필러 0.5cc <br>+ 콧볼 or 콧잔등보톡스",
                    "itemSubName": "[화/수/목 이벤트]<br>코필러(에피티크) 0.5cc <br>+ 콧볼 or 콧잔등보톡스",
                    "itemName_eng": "Nose Filler Neuramis 0.5cc",
                    "itemSubName_eng": "[Weekday 11 am-4 pm Event]<br>Correction of nose bridge and wings, Natural volume!",
                    "itemName_jp": "鼻フィラーニュラミス0.5㏄",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>鼻柱と鼻先を矯正してスリムに！",
                    "itemName_th": "ฟิลเลอร์จมูก  0.5 cc + โบท็อกซ์สันจมูก หรือ ปลายจมูก",
                    "itemSubName_th": "[โปรโมชั่นวันอังคาร/พุธ/พฤหัส]<br> ฟิลเลอร์ยี่ห้อ EPTQ จากเกาหลีใต่้",
                    "itemName_vn": "  Filler mũi Neuramis 0.5CC",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br>Điều chỉnh và làm thanh thoát sống mũi và chóp mũi!",
                    "cha": "374",
                    "cha_2": "374",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "코필러"
                },
                {
                    "id": "8345",
                    "groupId": "374",
                    "middleId": "45",
                    "originalPrice": "81000",
                    "discountedPrice": "49000",
                    "itemName": "리즈톡스(바디보톡스) 100u",
                    "itemSubName": "[화/수/목 이벤트]<br>승모근,허벅지,팔도 가능<br>울퉁불퉁 근육 슬림하게",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "リズトックス(ボディーボトックス）100ユニット",
                    "itemSubName_jp": "[火/水/木イベント]国産ボトックス<br>僧帽筋、太もも、腕可能<br>でこぼこの筋肉をスリムに",
                    "itemName_th": "",
                    "itemSubName_th": "",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "374",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "바디보톡스"
                },
                {
                    "id": "8346",
                    "groupId": "374",
                    "middleId": "45",
                    "originalPrice": "111000",
                    "discountedPrice": "69000",
                    "itemName": "리즈톡스(바디보톡스) 150u",
                    "itemSubName": "[화/수/목 이벤트]<br>승모근,허벅지,팔도 가능<br>울퉁불퉁 근육 슬림하게",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "リズトックス(ボディーボトックス）150ユニット",
                    "itemSubName_jp": "[火/水/木イベント]国産ボトックス<br>僧帽筋、太もも、腕可能<br>でこぼこの筋肉をスリムに",
                    "itemName_th": "",
                    "itemSubName_th": "",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "374",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "바디보톡스"
                },
                {
                    "id": "8347",
                    "groupId": "374",
                    "middleId": "45",
                    "originalPrice": "142000",
                    "discountedPrice": "89000",
                    "itemName": "리즈톡스(바디보톡스) 200u",
                    "itemSubName": "[화/수/목 이벤트]<br>승모근,허벅지,팔도 가능<br>울퉁불퉁 근육 슬림하게",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "リズトックス(ボディーボトックス)200ユニット",
                    "itemSubName_jp": "[火/水/木イベント]国産ボトックス<br>僧帽筋、太もも、腕可能<br>でこぼこの筋肉をスリムに",
                    "itemName_th": "",
                    "itemSubName_th": "",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "374",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "바디보톡스"
                },
                {
                    "id": "425",
                    "groupId": "0",
                    "middleId": "621",
                    "originalPrice": "120000",
                    "discountedPrice": "89000",
                    "itemName": "알라딘필(압출 포함)",
                    "itemSubName": "[화/수/목 이벤트]<br>가능부위 : 얼굴<br>압출+알라딘필+진정머미+마무리",
                    "itemName_eng": "Arm goosebumps peeling<br> M Peel + Aladdin Peel + Soothing Care",
                    "itemSubName_eng": "",
                    "itemName_jp": "腕鳥肌ピーリング<br>Mピール+アラジンピール+鎮静ケア",
                    "itemSubName_jp": "[オールタイムイベント]毛孔性角化症緩和、すべすべ肌作り！",
                    "itemName_th": "",
                    "itemSubName_th": "",
                    "itemName_vn": "Peeling cánh tay da gà<br>M Peel+ Aladdin Peel+Chăm sóc cân bằng",
                    "itemSubName_vn": "[ Khuyến mãi All time]<br> cải thiện sừng hóa lỗ chân lông, đem lại làn da trơn láng mịn màng!",
                    "cha": "374",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "바디 필링"
                },
                {
                    "id": "4438",
                    "groupId": "0",
                    "middleId": "85",
                    "originalPrice": "90000",
                    "discountedPrice": "59000",
                    "itemName": "알라딘필(압출 미포함)",
                    "itemSubName": "[화/수/목 이벤트]<br>가능부위 : 얼굴<br>알라딘필(압출 미포함)+진정머미+마무리",
                    "itemName_eng": "Aladdin Peel (Excluding Extrusion)",
                    "itemSubName_eng": "[Weekday 11AM~4PM Event]<br>Relieve Keratosis Pilaris, Create Smooth Skin!",
                    "itemName_jp": "アラジンピール（圧出含まず）+再生管理",
                    "itemSubName_jp": "【火/水/木イベント]<br>毛穴角化症の緩和、なめらか肌を作り！",
                    "itemName_th": "อะลาดินพิล (ไม่รวมการกดสิว)",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา ตั้งแต่ 16.00 - 19.00 น.]<br>ผลัดเซลล์ผิวเก่า เผยผิวใหม่ที่เนียนนุ่มชุ่มชื้นขึ้น",
                    "itemName_vn": "Aladdin Peel (không bao gồm nặn  mụm) + chăm sóc tái tạo da",
                    "itemSubName_vn": "[Khuyến mãi ba/tư/năm]<br> giảm sừng hóa lỗ chân lông,  khiến da trở nên mịn màng !",
                    "cha": "374",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "알라딘필"
                }
            ]
        },
        {
            "id": "14",
            "chainId": "1",
            "middleId": "42",
            "groupName": "해피아워(평일오전11시~4시)",
            "groupSubName": "[해피아워 EVENT] 평일 11시~16시까지 적용!",
            "dayOfTheWeek": "12345",
            "startDate": null,
            "endDate": null,
            "startTime": "11",
            "endTime": "16",
            "orderby": "1",
            "regDate": "2018-01-08 17:57:14",
            "selected": "1",
            "selected_list": "1",
            "startDate_list": "2018-01-01",
            "endDate_list": "2018-02-28",
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "3",
            "orderby_0": "0",
            "print_orderby_1": "1",
            "print_orderby_2": "2",
            "createAdminId": null,
            "lastUpdateAdminId": null,
            "groupName_eng": "Happy Hour (Weekdays from 11AM~4PM)",
            "groupSubName_eng": "",
            "groupName_jp": "ハッピーアワー(平日午前11時〜16時)",
            "groupSubName_jp": "",
            "groupName_th": "แฮปปี้อาวร์ (วันธรรมดา ตั้งแต่ 11.00 - 16.00 น.)",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,eng,jp,th,vn",
            "groupName_vn": "Happy Hour (Ngày thường từ 11 giờ sáng ~4 giờ chiều)",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "7643",
                    "groupId": "0",
                    "middleId": "76",
                    "originalPrice": "75000",
                    "discountedPrice": "49000",
                    "itemName": "프락셀(얼굴전체) + 크라이오셀<br>+ 마무리 + 마스크팩 3장",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "フラクセル（顔全体）+ PDRN<br>+水分アンプル+シートマスク",
                    "itemSubName_jp": "[平日午前11時〜午後4時イベント]<br>毛穴縮小/ニキビ跡<br>/傷跡の改善",
                    "itemName_th": "แฟร็กเซล(ทั่วทั้งใบหน้า)+PDRN<br>+แอมเพิลเพิ่มความชุ่มชื้น+มาส์กแผ่น",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา เวลา 11.00 - 16.00 น.]<br>ช่วยให้รูขุมขนดูตื้นขึ้น รอยสิวและรอยแผลเป็นดูจางลง",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "14",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "프락셀"
                },
                {
                    "id": "3590",
                    "groupId": "14",
                    "middleId": "50",
                    "originalPrice": "130000",
                    "discountedPrice": "69000",
                    "itemName": "입술필러 + 입꼬리필러<br>+ 입꼬리보톡스",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]<br>입술+입꼬리필러(아띠에르) 1cc <br>+ 입꼬리보톡스",
                    "itemName_eng": "Lip Filler + Lip Angle Filler + Lip Angle Botox",
                    "itemSubName_eng": "[Weekday 11AM~4PM Event]<br>Atiere 1cc",
                    "itemName_jp": "唇フィラー＋口角フィラー＋口角ボトックス",
                    "itemSubName_jp": "アティエル1㏄+口角ボトックス",
                    "itemName_th": "ฟิลเลอร์ยกมุมปาก+ริมฝีปาก 1cc<br> + โบท็อกซ์ยกมุมปาก (ยี่ห้อ Innotox)",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา เวลา 11.00 - 16.00 น.]<br>ยี่ห้อ Atiere 1cc",
                    "itemName_vn": "Filler môi + Filler khóe miệng<br>+ Botox khóe miệng(Innotox)",
                    "itemSubName_vn": "[Khuyến mãi ba/tư/năm]<br>Atiere 1cc",
                    "cha": "14",
                    "cha_2": "14",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "입꼬리보톡스/입꼬리필러"
                },
                {
                    "id": "8344",
                    "groupId": "14",
                    "middleId": "3514",
                    "originalPrice": "85000",
                    "discountedPrice": "59000",
                    "itemName": "로즈필",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]<br>로즈필+로즈솔루션러빙+자가세안+크라이오+로즈생잎마스크+모델링<br><br>천연비타민+AHA 필링으로<br>재생+미백+보습 효과",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "ローズピール",
                    "itemSubName_jp": "ローズピール+ローズソリューションラビング+洗顔+ローズ生葉マスク+クライオ+モデリング<br><br>天然ビタミン+ AHAピーリングで<br>再生+美白+保湿効果",
                    "itemName_th": "",
                    "itemSubName_th": "",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "14",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "로즈필"
                },
                {
                    "id": "7965",
                    "groupId": "0",
                    "middleId": "47",
                    "originalPrice": "155000",
                    "discountedPrice": "79000",
                    "itemName": "주름소멸패키지",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]<br>주름보톡스 3부위 + 더모톡신",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "しわ消滅パッケージ",
                    "itemSubName_jp": "しわボトックス3部位+ドマトクシン",
                    "itemName_th": "เซตหน้าเด้ง ลดริ้วรอย",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา เวลา 11.00 - 16.00 น.]<br>โบท็อกซ์ลดริ้วรอย 3 จุด + โบท็อกซ์ลิฟท์หน้า",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "14",
                    "cha_2": "14",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "주름보톡스"
                },
                {
                    "id": "3429",
                    "groupId": "14",
                    "middleId": "54",
                    "originalPrice": "270000",
                    "discountedPrice": "139000",
                    "itemName": "[3D얼굴필러] 에피티크 3cc",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]<br>정품정량 눈앞 개봉<br><br>앞광대, 팔자, 옆볼, 턱<br>(*해당 부위만 가능)",
                    "itemName_eng": "3D Contour Filler Atiere 3cc",
                    "itemSubName_eng": "[Weekday 11AM~4PM Event]<br> Jaw, Cheeks, Smile lines, Cheek bones",
                    "itemName_jp": "3D輪郭フィラーアティエル3㏄",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>あご、頬、ほうれい線、頬骨",
                    "itemName_th": "ฟิลเลอร์ใบหน้าแบบ 3D ยี่ห้อ EPTQ 3cc",
                    "itemSubName_th": " [โปรโมชั่นวันธรรมดา ตั้งแต่ 11.00 - 16.00 น.]<br>กราม, แก้ม, ร่องแก้ม, โหนกแก้ม",
                    "itemName_vn": "Filler đường viền 3D  Atiere 3cc",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br> Mở trước mắt sản phẩm chính hãng đúng liều lượng<br>cằm, má, rãnh má, má trước<br>(*Chỉ có thể tiêm những bộ phận tương ứng)",
                    "cha": "14",
                    "cha_2": "14",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "얼굴필러"
                },
                {
                    "id": "188",
                    "groupId": "0",
                    "middleId": "74",
                    "originalPrice": "29000",
                    "discountedPrice": "15000",
                    "itemName": "레이저토닝/IPL 1회",
                    "itemSubName": "[평일 오전11시~오후4시 이벤트]",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "レーザートーニング1回",
                    "itemSubName_jp": "[平日午前11時～4時イベント]シミ、色素、肌のトーン改善",
                    "itemName_th": "เลเซอร์โทนนิ่ง 1 ครั้ง",
                    "itemSubName_th": "",
                    "itemName_vn": "Laser Toning 1 lần",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều] tàn nhang, sắc tố đậm màu , cải  thiện  tone da",
                    "cha": "14",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "토닝"
                }
            ]
        },
        {
            "id": "774",
            "chainId": "1",
            "middleId": null,
            "groupName": "제모 올타임 EVENT",
            "groupSubName": "[올타임 EVENT] 평일, 주말 상관없이 올타임 적용!",
            "dayOfTheWeek": "123456",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "2",
            "regDate": "2020-02-26 18:00:22",
            "selected": "1",
            "selected_list": "0",
            "startDate_list": null,
            "endDate_list": null,
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "0",
            "orderby_0": "0",
            "print_orderby_1": "0",
            "print_orderby_2": "0",
            "createAdminId": "shwhdgml456",
            "lastUpdateAdminId": null,
            "groupName_eng": "",
            "groupSubName_eng": "",
            "groupName_jp": "",
            "groupSubName_jp": "",
            "groupName_th": "",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor",
            "groupName_vn": "",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "3182",
                    "groupId": "0",
                    "middleId": "128",
                    "originalPrice": "390000",
                    "discountedPrice": "249000",
                    "itemName": "[여성] 브라질리언+항문 제모 5회",
                    "itemSubName": "아포지플러스<br>공중타격방식 / 쿨링요법",
                    "itemName_eng": "[Women] Brazilian (Anus Included) Hair Removal 5 times",
                    "itemSubName_eng": "Apogee Plus<br>Air-knock method / Cooling method",
                    "itemName_jp": "女性ブラジリアン（肛門含み）脱毛5回",
                    "itemSubName_jp": "アポジプラス<br>空中打撃 / クーリング療法",
                    "itemName_th": "กำจัดขนบริเวณจุดซ่อนเร้นของคุณผู้หญิง (รวมทวารหนัก) 5 ครั้ง",
                    "itemSubName_th": "กำจัดขนด้วยเครื่อง Apogee Plus<br> การพ่นด้วยอากาศ / แอร์คูลลิ่ง",
                    "itemName_vn": "[Nữ giới] Triệt lông Vùng kín( Bao gồm hậu môn) 5 lần",
                    "itemSubName_vn": "Apogee+<br>Phương pháp không kích / Phương pháp Cooling",
                    "cha": "774",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "29",
                    "mainName": "여성 제모"
                },
                {
                    "id": "4912",
                    "groupId": "774",
                    "middleId": "127",
                    "originalPrice": "190000",
                    "discountedPrice": "99000",
                    "itemName": "[남성] 턱+인중 제모 5회",
                    "itemSubName": "아포지플러스<br>공중타격방식 / 쿨링요법",
                    "itemName_eng": "[Male] Jaw + Philtrum Hair Removal 5 sessions",
                    "itemSubName_eng": "[Weekday Limited All-time Event]<br>Apogee Plus<br>Air-Knock Method / Cooling Technique",
                    "itemName_jp": "【メンズ】アゴ+人中脱毛5回",
                    "itemSubName_jp": "【平日限定オールタイムイベント]<br>アポジプラス<br>空中打撃方式/クーリング療法",
                    "itemName_th": "[ชาย] เลเซอร์หนวด + เครา 5 ครั้ง",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา]<br>กำจัดขนด้วยเครื่อง Apogee Plus<br>กำจัดขนแบบคูลลิ่ง /ไม่ระคายเคือง",
                    "itemName_vn": "",
                    "itemSubName_vn": "",
                    "cha": "774",
                    "cha_2": "771",
                    "cha_0": "0",
                    "categoryId": "29",
                    "mainName": "남성 제모"
                },
                {
                    "id": "4913",
                    "groupId": "514",
                    "middleId": "127",
                    "originalPrice": "290000",
                    "discountedPrice": "159000",
                    "itemName": "[남성] 턱+볼+구렛나루<br>+인중+윗목 제모 5회",
                    "itemSubName": "아포지플러스<br>공중타격방식 / 쿨링요법<br><br>옵션) 진정관리 1회 추가시 <br>+2만5천원",
                    "itemName_eng": "[Male] Jaw + Cheek+ Sideburns+ Philtrun+ Back Neck Hair Removal 5 sessions",
                    "itemSubName_eng": "[Weekday Limited All-time Event]<br>Apogee Plus<br>Air-Knock Method / Cooling Technique",
                    "itemName_jp": "【メンズ】顎+頬+もみあげ<br>+人中+上首脱毛5回",
                    "itemSubName_jp": "【平日限定オールタイムイベント]<br>アポジプラス<br>空中打撃方式/冷却療法<br><br>オプション）鎮静管理追加時+₩25,000",
                    "itemName_th": "[ชาย]เลเซอร์ขน บริเวณต้นคอ+จอน+หนวด+เครา 5 ครั้ง",
                    "itemSubName_th": "[โปรโมชั่นตลอดทั้งวัน]<br>กำจัดขนด้วยเครื่อง Apogee Plus<br> การพ่นด้วยอากาศ / แอร์คูลลิ่ง",
                    "itemName_vn": "[Nam giới] Triệt lông  Cằm + M á +Râu quai  nón<br>+ Nhân trung +Cổ trên 5 lần ",
                    "itemSubName_vn": "[ Khuyến mãi All time giới hạn ngày thường]<br> Apogee+<br>Phương pháp không kích / Phương pháp Cooling",
                    "cha": "774",
                    "cha_2": "771",
                    "cha_0": "0",
                    "categoryId": "29",
                    "mainName": "남성 제모"
                },
                {
                    "id": "5366",
                    "groupId": "514",
                    "middleId": "127",
                    "originalPrice": "600000",
                    "discountedPrice": "319000",
                    "itemName": "[남성] 브라질리언 제모 5회<br>(항문포함)",
                    "itemSubName": "아포지플러스<br>공중타격방식 / 쿨링요법",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "【メンズ】ブラジリアン脱毛5回<br>（肛門を含む）",
                    "itemSubName_jp": "【平日限定オールタイムイベント]<br>アポジプラス<br>空中打撃方式/クーリング療法",
                    "itemName_th": "[ชาย] เลเซอร์ขน บริเวณจุดซ่อนเร้น 5 ครั้ง <br>(รวมทวารหนัก)",
                    "itemSubName_th": "[โปรโมชั่นตลอดทั้งวัน]<br>กำจัดขนด้วยเครื่อง Apogee Plus การพ่นด้วยอากาศ / แอร์คูลลิ่ง",
                    "itemName_vn": "[Nam giới]  Triệt  lông vùng kín 5 lần<br>( Bao gồm hậu môn)",
                    "itemSubName_vn": "[ Khuyến mãi All time giới hạn ngày thường]<br> Apogee+<br>Phương pháp không kích / Phương pháp Cooling",
                    "cha": "774",
                    "cha_2": "771",
                    "cha_0": "0",
                    "categoryId": "29",
                    "mainName": "남성 제모"
                }
            ]
        },
        {
            "id": "17",
            "chainId": "1",
            "middleId": "42",
            "groupName": "올타임 EVENT",
            "groupSubName": "[올타임 EVENT] 평일, 주말 상관없이 올타임 적용!",
            "dayOfTheWeek": "123456",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "3",
            "regDate": "2018-01-08 17:57:14",
            "selected": "1",
            "selected_list": "1",
            "startDate_list": "2018-01-01",
            "endDate_list": "2018-02-28",
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "5",
            "orderby_0": "1",
            "print_orderby_1": "3",
            "print_orderby_2": "4",
            "createAdminId": null,
            "lastUpdateAdminId": null,
            "groupName_eng": "All-time Events",
            "groupSubName_eng": "",
            "groupName_jp": "オールタイム EVENT",
            "groupSubName_jp": "",
            "groupName_th": "ออลไทม์ อีเว้นท์",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,eng,jp,th,vn",
            "groupName_vn": "Khuyến mãi All-time",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "1729",
                    "groupId": "0",
                    "middleId": "42",
                    "originalPrice": "55000",
                    "discountedPrice": "29000",
                    "itemName": "턱보톡스(이노톡스)50u + 아큐주사 3cc",
                    "itemSubName": "",
                    "itemName_eng": "Jaw Botox + Tightening",
                    "itemSubName_eng": "[Weekday 11 am-4 pm Event]<br> Reduce and Tighten! Let\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\'s find the missing jawline! ",
                    "itemName_jp": "エラボトックス＋タイトニング",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>減らして、引っ張って！なくなったあごラインを取り戻そう！",
                    "itemName_th": "โบท็อกซ์ลดกราม  +  ฉีด Tightening",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา เวลา 11.00-16.00 น.]<br>ช่วยให้หน้าเรียวเป็น เห็น V Line ชัดเจน",
                    "itemName_vn": "Botox cằm + Tightening",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br>Làm giảm và kéo căng!Hãy cùng tìm viền cằm bị mất tích!",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "턱보톡스"
                },
                {
                    "id": "3729",
                    "groupId": "0",
                    "middleId": "89",
                    "originalPrice": "35000",
                    "discountedPrice": "19000",
                    "itemName": "아쿠아필(AHA얼굴전체<br>+BHA T존) + 크라이오",
                    "itemSubName": "모공청소 / 피지제거 / 각질케어",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "アクアピールバタフライゾーン＋クライオセル鎮静",
                    "itemSubName_jp": "[平日午前11時～4時イベント]",
                    "itemName_th": "อควาพิลเฉพาะบริเวณจมูกและแก้ม + Cryo",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา ตั้งแต่ 11.00 - 16.00 น.]",
                    "itemName_vn": "Aqua Peel  vùng nabi + Cryo cân bằng",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "아쿠아필"
                },
                {
                    "id": "186",
                    "groupId": "0",
                    "middleId": "3515",
                    "originalPrice": "70000",
                    "discountedPrice": "39000",
                    "itemName": "그린필(화이트닝필링)",
                    "itemSubName": "그린필+크라이오<br>+화이트오투덤마스크+모델링<br><br>\n기미+주근깨+색소침착에<br>효과적인 필링",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "アクアピール＋ㇲペクトラピール",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>毛穴一掃 + 殺菌 + 美白 + 再生",
                    "itemName_th": "อควาพิล + สเปคตร้าพิล",
                    "itemSubName_th": "",
                    "itemName_vn": "Aqua Peel+ Spectra Peel",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br>làm sạch lỗ chân lông +  diệt vi khuẩn +  làm trắng +  tái tạo da",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "그린필"
                },
                {
                    "id": "1098",
                    "groupId": "0",
                    "middleId": "71",
                    "originalPrice": "39000",
                    "discountedPrice": "20000",
                    "itemName": "영양주사",
                    "itemSubName": "백옥,신데렐라,비타민C,<br>\n감초,마늘,비타민D 중 1회<br><br>\n면역력증진! 피부톤개선!",
                    "itemName_eng": "Nutrition Injection 1 time",
                    "itemSubName_eng": "[Weekday 4pm - 7pm Event]<br>Choose 1 from White Jade/Garlic/Licorice/Cinderella<br>/Vitamin C/Vitamin D",
                    "itemName_jp": "栄養注射1回",
                    "itemSubName_jp": "[平日午後4時~7時イベント]<br>白玉注射・シンデレラ注射・甘草注射・にんにく注射・ビタミンC・ビタミンDの中で1つ選択",
                    "itemName_th": "ฉีดเพิ่มวิตามินให้ร่างกาย 1 ครั้ง",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา ตั้งแต่ 16.00 - 19.00 น.]<br>เลือกเฉพาะอย่างใดอย่างหนึ่งเท่านั้น ไวท์เทนนิ่ง/กระเทียม/ชะเอม/ซินเดอเรลล่า<br>/วิตามินC/วิตามินD",
                    "itemName_vn": "Tiêm dinh dưỡng  1 lần",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 4 giờ chiều ~ 7 giờ chiều ]<br> Chọn 1 trong   Tiêm trắng ngọc bích / Tiêm tỏi/ Tiêm cam thảo/  Tiêm Cinderella<br>/ Tiêm Vietam in C/ Tiêm Vitamin D",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "항노화주사"
                },
                {
                    "id": "288",
                    "groupId": "0",
                    "middleId": "71",
                    "originalPrice": "59000",
                    "discountedPrice": "30000",
                    "itemName": "영양주사 + 크라이오 + 모델링",
                    "itemSubName": "백옥,신데렐라,비타민C,<br>\n감초,마늘,비타민D 중 1회<br><br>\n면역력증진! 피부톤개선!",
                    "itemName_eng": "Morning Nutrition Injection",
                    "itemSubName_eng": "[Weekdays from 11am to 4pm]<br>Skin Whitening Injection/ Cinderella Injection/ Garlic Injection/ Licorice Injection/ Vitamin C Injection/ Vitamin D Injection",
                    "itemName_jp": "モーニング栄養注射",
                    "itemSubName_jp": "[平日午前11時～4時イベント]<br>白玉注射・シンデレラ注射・甘草注射・にんにく注射・ビタミンC・ビタミンD",
                    "itemName_th": "ฉีด Morning Nutrition",
                    "itemSubName_th": "[โปรโมชั่นวันธรรมดา 11.00 - 16.00 ]ไวท์เทนนิ่ง/ซินเดอเรลล่า/ชะเอม/กระเทียม/วิตามิน D/วิตามิน C",
                    "itemName_vn": "Tiêm dinh dưỡng buổi sáng",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]<br>Tiêm trắng ngọc bích / Tiêm Cinderella/ Tiêm cam thảo /Tiêm tỏi/ Tiêm Vitamin C/Tiêm Vitamin D",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "항노화주사"
                },
                {
                    "id": "3864",
                    "groupId": "17",
                    "middleId": "2948",
                    "originalPrice": "370000",
                    "discountedPrice": "199000",
                    "itemName": "에어슈링크",
                    "itemSubName": "에어젯리프팅 100샷 <br>+ 슈링크 200샷 <br>+ 아큐주사 6cc",
                    "itemName_eng": "Air jet Lifting 100 shots",
                    "itemSubName_eng": "Up to forehead, Lifting effects UP!<br>Natural lifting by air pressure",
                    "itemName_jp": "エアジェットリフト100ショット",
                    "itemSubName_jp": "額までリフティング効果 UP!<br>高気圧刺激でたるみのないリフティング",
                    "itemName_th": "ดึงกรอบหน้า + ยกกระชับ",
                    "itemSubName_th": "แอร์เจ็ต ลิฟทิ่ง 100 ช็อต + ชูริงค์ 200 ช็อต + ฉีดลดแฟต ACU 6cc",
                    "itemName_vn": " Air jet Lifting    100 shots",
                    "itemSubName_vn": "Đến tận trán hiệu quả Lifing  UP!,<br> Lifting thu nhỏ tối đa mỡ má bằng tác động của không khí",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "41",
                    "mainName": "에어젯리프팅"
                },
                {
                    "id": "7968",
                    "groupId": "17",
                    "middleId": "63",
                    "originalPrice": "255000",
                    "discountedPrice": "139000",
                    "itemName": "V핏 달걀주사",
                    "itemSubName": "턱보톡스(이노톡스)<br>+광대보톡스(이노톡스)<br>+프리미엄아큐주사 12cc<br>+블러톡스<br><br> 용량은 업! 가격은 다운!",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "Vフィットたまご注射",
                    "itemSubName_jp": "エラボトックス（イノトックス）+頬骨ボトックス（イノトックス）+プレミアムアキュ12cc+ブラトックス<br>容量はアップ！価格はダウン！",
                    "itemName_th": "เซต วีไลน์ ซุปเปอร์เอ้ก",
                    "itemSubName_th": "โบท็อกซ์กราม + โบท็อกซ์โหนกแก้ม หรือ ริ้วรอย 1 จุด <br>+ Premium ACU  12 cc + เบลอท็อกซ์<br>หน้าเรียวแบบจัดเต็ม!",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "25",
                    "mainName": "슈퍼달걀주사"
                },
                {
                    "id": "4071",
                    "groupId": "17",
                    "middleId": "47",
                    "originalPrice": "25000",
                    "discountedPrice": "15000",
                    "itemName": "주름보톡스 1부위",
                    "itemSubName": "이마, 미간, 눈가, 눈밑,<br>콧잔등, 자갈턱, 콧볼",
                    "itemName_eng": "Anti-wrinkle Botox 1 part",
                    "itemSubName_eng": "Forehead, Frown, Eye rims, Nose Bridge, Chin crease, Nose wings",
                    "itemName_jp": "シワボトックス1部位",
                    "itemSubName_jp": "額、眉間、目元、目の下、鼻筋、梅干しジワ、小鼻",
                    "itemName_th": "โบท็อกซ์ลดริ้วรอย 1 จุด",
                    "itemSubName_th": "หน้าผาก, ระหว่างคิ้ว,รอยตีนกา,ใต้ตา,คาง, สันจมูก",
                    "itemName_vn": " Botox cải thiện nếp nhăn 1bộ phận",
                    "itemSubName_vn": "Trán, giữa hai lông  mày,bờ mắt, dưới mắt, đầu sống mũi,cằm, cánh mũi",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "주름보톡스"
                },
                {
                    "id": "182",
                    "groupId": "17",
                    "middleId": "47",
                    "originalPrice": "99000",
                    "discountedPrice": "55000",
                    "itemName": "주름보톡스 5부위(풀페이스)",
                    "itemSubName": "이마, 미간, 눈가, 눈밑,<br>콧잔등, 자갈턱, 콧볼",
                    "itemName_eng": "Anti-wrinkle Botox 3 parts",
                    "itemSubName_eng": "[Weekday 11 am-4 pm Event] Choose 3 parts from Forehead, Eye rims, Frown, Nose bridge.Chin crease",
                    "itemName_jp": "シワボトックス5部位",
                    "itemSubName_jp": "額、眉間、目尻、目元、<br>鼻筋、梅干しシワ、小鼻",
                    "itemName_th": "โบท็อกซ์ลดริ้วรอย 5 จุด (ทั่วทั้งหน้า)",
                    "itemSubName_th": "สามารถเลือกได้ 5 จุด ไม่ว่าจะเป็นหน้าผาก, ระหว่างคิ้ว,รอยตีนกา,ใต้ตา,คาง, สันจมูก",
                    "itemName_vn": " Botox cải thiện nếp nhăn 3 bộ phận",
                    "itemSubName_vn": "[Khuyến mãi ngày thường 11 giờ sáng ~ 4 giờ chiều]  Chọn  3 bộ phận trong số trán ,bờ mắt, giữa hai lông mày,đầu sống mũi,cằm",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "주름보톡스"
                },
                {
                    "id": "2323",
                    "groupId": "17",
                    "middleId": "65",
                    "originalPrice": "80000",
                    "discountedPrice": "50000",
                    "itemName": "프리미엄 아큐주사 1회 (3cc)",
                    "itemSubName": "아큐주사 업그레이드 Ver.",
                    "itemName_eng": "Premium Acu Injection 1 time (3cc)",
                    "itemSubName_eng": "Acu Injection Upgraded Ver.",
                    "itemName_jp": "プレミアムアキュ注射1回(3㏄)",
                    "itemSubName_jp": "アキュ注射アップグレード Ver.",
                    "itemName_th": "ฉีด Premium ACU 1 ครั้ง (3cc)",
                    "itemSubName_th": "ACU เวอร์ชั่นอัพเกรดใหม่ พรีเมี่ยมกว่าเดิม",
                    "itemName_vn": "Tiêm Acu Premium  1 lần (3cc)",
                    "itemSubName_vn": "Tiêm Acu Upgraded Ver.",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "25",
                    "mainName": "NEW 아큐주사"
                },
                {
                    "id": "3863",
                    "groupId": "17",
                    "middleId": "65",
                    "originalPrice": "170000",
                    "discountedPrice": "120000",
                    "itemName": "프리미엄 아큐주사 3회 (9cc)",
                    "itemSubName": "아큐주사 업그레이드 Ver.",
                    "itemName_eng": "Premium Acu Injection 3 times (9cc)",
                    "itemSubName_eng": "Acu Injection Upgraded Ver.",
                    "itemName_jp": "プレミアムアキュ注射3回 (9㏄)",
                    "itemSubName_jp": "アキュ注射アップグレード Ver.",
                    "itemName_th": "ฉีด Premium ACU 3 ครั้ง (9cc)",
                    "itemSubName_th": "ACU เวอร์ชั่นอัพเกรดใหม่ พรีเมี่ยมกว่าเดิม",
                    "itemName_vn": " Tiêm Acu Premium  3 lần (9cc)",
                    "itemSubName_vn": "Tiêm Acu Ver. upgraded",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "25",
                    "mainName": "NEW 아큐주사"
                },
                {
                    "id": "8176",
                    "groupId": "17",
                    "middleId": "60",
                    "originalPrice": "530000",
                    "discountedPrice": "279000",
                    "itemName": "풀페이스 리쥬란",
                    "itemSubName": "리쥬란 2cc + 아이리쥬란 1cc <br>+ 시트마스크",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "フルフェイスリジュラン",
                    "itemSubName_jp": "リジュラン2cc+アイリジュラン1ccン+シートマスク",
                    "itemName_th": "[โปรหน้าใส] ฉีดรีจูรัน ทั่วทั้งหน้า",
                    "itemSubName_th": "รีจูรันใบหน้า 2cc +  รีจูรันใต้ตา 1cc + ชีทมาส์ก",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "피부재생 주사"
                },
                {
                    "id": "7854",
                    "groupId": "17",
                    "middleId": "57",
                    "originalPrice": "490000",
                    "discountedPrice": "259000",
                    "itemName": "[풀페이스 슈링크패키지]<br>슈링크 300샷<br>+ V슈링크 100샷<br>+ 아이슈링크 100샷<br>+ 프리미엄아큐주사 3cc",
                    "itemSubName": "이중턱개선<br> / 피부탄력생성 / 눈가잔주름<br> 얼굴전체 탄력을 한번에 잡아주자!",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "【フルフェイスシュリンクパッケージ]<br>シュリンク300ショット<br>+ Vシュリンク100ショット<br>+アイシュリンク100ショット<br>+プレミアムアキュ注射3cc",
                    "itemSubName_jp": "二重顎改善<br>/皮膚の弾力性を生成/目元の小ジワ<br>顔全体の弾力性を一度に手に入れるチャンス！",
                    "itemName_th": "[แพ็กเกจ ชูริงค์ เซตใหญ่]<br>ชูริงค์ 300 ช็อต<br>+ Vชูริงค์ที่เหนียง 100 ช็อต<br>+ชูริงค์ใต้ตา 100 ช็อต<br>+ Premium ACU สลายไขมัน 3cc",
                    "itemSubName_th": "ยกกระชับหน้า<br>สลายเหนียง/ยกกระชับใต้ตา<br>เพิ่มคอลลาเจนให้ผิวหน้าและช่วยสลายไขมันบริเวณใบหน้า",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "슈링크리프팅"
                },
                {
                    "id": "7644",
                    "groupId": "17",
                    "middleId": "57",
                    "originalPrice": "180000",
                    "discountedPrice": "99000",
                    "itemName": "슈링크 300샷 + 타이트닝주사",
                    "itemSubName": "피부탄력 up + 턱라인 집중 리프팅",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "シュリンク300ショット+タイトニング注射",
                    "itemSubName_jp": "皮膚弾力UP+フェイスライン集中リフティング",
                    "itemName_th": "ชูริงค์ 300 ช็อต + ฉีด Tightening",
                    "itemSubName_th": "อัพผิวหน้าให้กระชับ + หน้าเรียวเล็กขึ้น",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "슈링크리프팅"
                },
                {
                    "id": "341",
                    "groupId": "17",
                    "middleId": "57",
                    "originalPrice": "245000",
                    "discountedPrice": "129000",
                    "itemName": "슈링크 400샷 + 타이트닝주사",
                    "itemSubName": "피부탄력 up + 턱라인 집중 리프팅",
                    "itemName_eng": "Shurink 400 shots + Tightening Injection",
                    "itemSubName_eng": "Skin elasticity UP + Jawline focused Lifting",
                    "itemName_jp": "シュリンクリフト400ショット＋タイトニング注射",
                    "itemSubName_jp": "[オールタイムイベント]<br>肌の弾力UP＋あごライン集中リフト",
                    "itemName_th": "ชูริงค์ 400 ช็อต + ฉีด Tightening",
                    "itemSubName_th": "อัพผิวหน้าให้กระชับ + หน้าเรียวเล็กขึ้น",
                    "itemName_vn": "Shurink 400 shots +  Tiêm Tightening",
                    "itemSubName_vn": "Độ đàn hồi của da up + Lifting tập trung khuôn cằm",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "슈링크리프팅"
                },
                {
                    "id": "6250",
                    "groupId": "17",
                    "middleId": "57",
                    "originalPrice": "500000",
                    "discountedPrice": "269000",
                    "itemName": "슈링크 300샷 3회",
                    "itemSubName": "울트라포머3 / 레이저리프팅",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "シュリンク300ショット 3回",
                    "itemSubName_jp": "ウルトラフォーマー3/レーザーリフティング",
                    "itemName_th": "ชูริงค์ 300 ช็อต 3 ครั้ง",
                    "itemSubName_th": "เลเซอร์ยกกระชับ / อัลตร้าฟอร์เมอร์ 3",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "슈링크리프팅"
                },
                {
                    "id": "6597",
                    "groupId": "0",
                    "middleId": "3401",
                    "originalPrice": "130000",
                    "discountedPrice": "69000",
                    "itemName": "제스너 스케일링<br>(압출포함)",
                    "itemSubName": "모공, 화농성여드름, 닭살피부 개선!",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "★NEW★<br>ジェスナースケーリング<br>（押出あり）",
                    "itemSubName_jp": "毛穴、化膿性にきび肌の改善！",
                    "itemName_th": "★บริการใหม่★<br>Jessner Peel<br>(รวมกดสิว)",
                    "itemSubName_th": "ช่วยผลัดผิวที่มีรอยสิว<br>เป็นสิวหนอง,รูขุมขนกว้าง",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "제스너 스케일링"
                },
                {
                    "id": "6598",
                    "groupId": "17",
                    "middleId": "3401",
                    "originalPrice": "69000",
                    "discountedPrice": "39000",
                    "itemName": "제스너 스케일링<br>(압출미포함)",
                    "itemSubName": "모공, 화농성여드름, 닭살피부 개선!",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "★NEW★<br>ジェスナースケーリング<br>（押出なし）",
                    "itemSubName_jp": "毛穴、化膿性にきび肌の改善！",
                    "itemName_th": "★บริการใหม่★<br>Jessner Peel<br>(ไม่รวมกดสิว)",
                    "itemSubName_th": "ช่วยผลัดผิวที่มีรอยสิว<br>เป็นสิวหนอง,รูขุมขนกว้าง",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "제스너 스케일링"
                },
                {
                    "id": "5618",
                    "groupId": "17",
                    "middleId": "3353",
                    "originalPrice": "165000",
                    "discountedPrice": "99000",
                    "itemName": "카프리레이저 + 모델링 1회",
                    "itemSubName": "여드름의 근본적인 원인인<br>피지선 파괴 효과와<br>박테리아 살균 효과를 동시에!<br><br>#트러블개선 #피지살균 <br>#피지조절 #여드름치료",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "【NEW！】<br>カプリレーザー+モデリング1回",
                    "itemSubName_jp": "にきびの根本的な原因である<br>皮脂腺破壊効果と<br>バクテリア殺菌効果を同時に！<br><br>＃トラブル改善＃皮脂殺菌<br>＃皮脂調節＃にきび治療",
                    "itemName_th": "[ใหม่!]<br>CAPRI Laser + โมเดลลิ่งมาส์ก 1 ครั้ง",
                    "itemSubName_th": "เลเซอร์สำหรับผู้ที่หน้ามัน เป็นสิว <br>และช่วยกำจัดแบคทีเรียบนใบหน้า<br><br>#กำจัดสิว #ลดความมันบนใบหน้า <br>#ควบคุมความมัน # แก้ไขเรื่องสิว",
                    "itemName_vn": "[NEW!]<br> Laser Capri  +  Mặt nạ cao su 1 lần",
                    "itemSubName_vn": " Loại bỏ đồng thời  vi khuẩn  <br> và phá hủy tuyến bã nhờn <br> là nguyên nhân cơ bản gây ra mụn!<br><br># Cải thiện mụn đầu đen # Diệt khuẩn tuyến nhờn <br># Điều tiết bã nhờn# Trị mụn",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "카프리레이저"
                },
                {
                    "id": "5065",
                    "groupId": "17",
                    "middleId": "60",
                    "originalPrice": "380000",
                    "discountedPrice": "210000",
                    "itemName": "리쥬란 아이힐러 2cc",
                    "itemSubName": "눈가전용 리쥬란힐러 <br>눈가 잔주름, 탄력",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "リジュラン目元ヒーラー2cc",
                    "itemSubName_jp": "目元専用リジュランヒーラー<br>目元小じわ、弾力",
                    "itemName_th": "[NEW] ฉีด Rejuran Healer บริเวณใต้ตา 2cc",
                    "itemSubName_th": "ตัวช่วยให้ร่องลึกใต้ตาดูตื้นขึ้น<br>ช่วยให้รอยตีนกาตื้นขึ้นอย่างเห็นได้ชัด",
                    "itemName_vn": "Rejuran Healer 2cc",
                    "itemSubName_vn": "Rejuran Healer chuyên dụng cho bờ mắt <br>nếp nhăn nhỏ ở bờ mắt, đàn hồi",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "피부재생 주사"
                },
                {
                    "id": "3733",
                    "groupId": "17",
                    "middleId": "42",
                    "originalPrice": "35000",
                    "discountedPrice": "19000",
                    "itemName": "턱보톡스 50U 이노톡스",
                    "itemSubName": "정품정량 눈 앞 개봉",
                    "itemName_eng": "Jaw Botox (50U) Innotox",
                    "itemSubName_eng": "Original product & accurate dosage/ Opening Innotox original product on the site",
                    "itemName_jp": "エラボトックス50ユニット、イノトックス",
                    "itemSubName_jp": "正品!定量!目の前で開封！",
                    "itemName_th": "โบท็อกซ์กราม ยี่ห้อ Innotox 50U",
                    "itemSubName_th": "ผลิตภัณฑ์ของแท้ไม่เจือปน เปิดเมื่อใช้งานเท่านั้น",
                    "itemName_vn": " Botox cằm 50U  Innotox",
                    "itemSubName_vn": "Mở trước  mắt sản phẩm chính hãng đúng liều lượng",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "턱보톡스"
                },
                {
                    "id": "4902",
                    "groupId": "17",
                    "middleId": "42",
                    "originalPrice": "120000",
                    "discountedPrice": "79000",
                    "itemName": "턱보톡스 50U 제오민",
                    "itemSubName": "독일제 정품정량 눈 앞 개봉",
                    "itemName_eng": "Jaw Botox Xeomin 50U",
                    "itemSubName_eng": "Original Product Opened on the Site",
                    "itemName_jp": "エラボトックス50ユニット ジェオミン",
                    "itemSubName_jp": "ドイツ製の正品!定量!目の前で開封！",
                    "itemName_th": "โบท็อกซ์ลดกราม Xeomin 50U",
                    "itemSubName_th": "สามารถเปิดกล่องเช็คผลิตภัณฑ์ได้",
                    "itemName_vn": "Botox cằm  50U Xeomin",
                    "itemSubName_vn": "  Mở trước  mắt sản phẩm chính hãng Đứcđúng liều lượng ",
                    "cha": "17",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "12",
                    "mainName": "턱보톡스"
                },
                {
                    "id": "3860",
                    "groupId": "17",
                    "middleId": "51",
                    "originalPrice": "210000",
                    "discountedPrice": "150000",
                    "itemName": "바비코 2줄",
                    "itemSubName": "코끝 2줄<br>코끝 라인의 각도 개선 효과",
                    "itemName_eng": "Barbie Nose 2 threads",
                    "itemSubName_eng": "Wanna-be Nose Line! High Nose Bridge, Completed Nose Tip",
                    "itemName_jp": "バビコ2本",
                    "itemSubName_jp": "鼻先2本<br>鼻先ラインの角度改善効果!",
                    "itemName_th": "ร้อยไหมจมูกทรงบาร์บี้ 2 เส้น",
                    "itemSubName_th": "จมูกสวยดั่งใจ! <br>ปรับให้ดั้งและปลายจมูกโด่งสวยขึ้น",
                    "itemName_vn": "Mũi barbie 2 sợi",
                    "itemSubName_vn": "Chóp mũi 2 sợi<br>Hiệu quả cải thiện góc độ đường  chóp mũi ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "하이코/바비코"
                },
                {
                    "id": "4445",
                    "groupId": "17",
                    "middleId": "113",
                    "originalPrice": "89000",
                    "discountedPrice": "45000",
                    "itemName": "LDM 보습,재생 케어 1회",
                    "itemSubName": "탄력과 함께 수분까지 팡팡!",
                    "itemName_eng": "LDM Moisturizing, Regeneration Care 1 session",
                    "itemSubName_eng": "Elasticity, Moisture UP UP!",
                    "itemName_jp": "LDM保湿、再生ケア1回",
                    "itemSubName_jp": "弾力性と一緒に水分までパンパンに！",
                    "itemName_th": "LDM เพิ่มความชุ่มชื้น  ผิวเด้งใส 1 ครั้ง",
                    "itemSubName_th": "อัพผิวหน้าให้ดูอิ่มน้ำและเด้งกระชับ!",
                    "itemName_vn": "LDM  dưỡng  ẩm, chăm sóc tái tạo da 1 lần",
                    "itemSubName_vn": "Từ đàn hồi  cho đến dưỡng ẩm hoàn hảo!",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "28",
                    "mainName": "LDM"
                },
                {
                    "id": "3598",
                    "groupId": "17",
                    "middleId": "3160",
                    "originalPrice": "130000",
                    "discountedPrice": "80000",
                    "itemName": "피코토닝 + 모델링 1회",
                    "itemSubName": "프리미엄 토닝레이저, <br>빠르고 강한 화이트닝 , 색소개선<br><br>옵션) 피코 잡티제거 zoom pass <br>(짙은색소 집중) <br>大 (명함크기) +4만원 <br>中 (500원 동전크기) +2.5만원 <br>小 (10원 동전크기) +1만원",
                    "itemName_eng": "Pico Toning + Modeling 1 session",
                    "itemSubName_eng": "Premium Toning Laser, <br> Quick and Effective Whitening, Improve Pigmentation<br>Option)Pico Blemish Clear Zoom Pass (Deep pigmentation focused)<br>Big(Business card size) ₩40,000 <br>Middle ( ₩500 Coin size) ₩25,000<br> Small(₩10 Coin size) ₩10,000",
                    "itemName_jp": "ピコトーニング＋モデリングパック1回",
                    "itemSubName_jp": "プレミアムトーニングレーザー、早くて強いホワイトニング、色素改善<br>オプション) ピコくすみ除去 zoom pass (濃い色素集中) <br>大 (名刺サイズ) 4万ウォン <br>中 (500ウォン玉サイズ) 2.5万ウォン <br>小 (10ウォン玉サイズ) 1万ウォン",
                    "itemName_th": "พิโคโทนนิ่ง + โมเดลลิ่งมาส์ก 1 ครั้ง",
                    "itemSubName_th": "พรีเมี่ยมโทนนิ่งเลเซอร์, <br>ช่วยปรับสภาพผิวให้ขาวใสขึ้นอย่างรวดเร็ว<br>ตัวเลือก) zoom pass พิโคที่ช่วยขจัดจุดด่างดำ (เน้นเฉพาะการกำจัดเม็ดสีที่เข้ม) <br>ขนาดใหญ่ (ขนาดเท่านามบัตร) 40,000 วอน <br>ขนาดกลาง (ขนาดเท่าเหรียญ 500 วอน) 25,000 วอน <br>ขนาดเล็ก(ขนาดเท่าเหรียญ 10 วอน) 10,000 วอน",
                    "itemName_vn": "Pico Toning + mặt nạ cao su 1 lần ",
                    "itemSubName_vn": "Premium Toning Laser, <br> Làm trắng  nhanh và hiệu quả ,  cải thiện sắc tố<br><br>Option) Loại bỏ  tàn nhang  Pico  zoom pass <br>(Tập trung vùng sắc tố đậm) <br>大 (To bằng tấm danh thiếp) 40.000won <br>中 (To bằng đồng xu 500won) 25.000 won <br>小 (To bằng đồng xu 10won) 10.000won",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "27",
                    "mainName": "피코슈어 레이저토닝"
                },
                {
                    "id": "2522",
                    "groupId": "0",
                    "middleId": "54",
                    "originalPrice": "99000",
                    "discountedPrice": "79000",
                    "itemName": "아띠에르 필러 1cc",
                    "itemSubName": "정품정량 눈앞개봉!<br>안전성요건을 갖춘 <br>히알루론산 성분의 필러<br>(애교제외/모든부위 가능)",
                    "itemName_eng": "Atiere Filler 1cc ",
                    "itemSubName_eng": "Filler Which Includes Hyaluronic Acid from Domestic Medytox Products<br>(All parts except for eye-bag areas)",
                    "itemName_jp": "アティエルフィラー1㏄",
                    "itemSubName_jp": "韓国産メディトックス製品でヒアルロン酸成分のフィラー<br>(涙袋除外・全部位可能)",
                    "itemName_th": "ฟิลเลอร์ยี่ห้อ Atiere 1cc",
                    "itemSubName_th": "ฟิลเลอร์กรดไฮยาลูรอนิค ผลิตจากบริษัท Mydytox ประเทศเกาหลีใต้<br>(ฉีดได้ทุกส่วนยกเว้นบริเวณใต้ตา)",
                    "itemName_vn": "Filler Atiere  1cc",
                    "itemSubName_vn": "Mở trước mắt sản phẩm chính hãng đúng liều lượng!<br>là sản phẩm Medytox trong nước<br>Filler với thành phần hyaluronic<br>(Ngoại trừ bọng mắt/Tất cả các bộ phận đều được)",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "얼굴필러"
                },
                {
                    "id": "37",
                    "groupId": "0",
                    "middleId": "107",
                    "originalPrice": "990000",
                    "discountedPrice": "599000",
                    "itemName": "울쎄라 300샷 <br>+ 프리미엄아큐주사 9cc",
                    "itemSubName": "원조 프리미엄 레이저 리프팅",
                    "itemName_eng": "Original Product Ultra 300 shots",
                    "itemSubName_eng": "Available for checking of original tip opening<br> Original Premium Laser Lifting ",
                    "itemName_jp": "正品ウルセラ300ショット",
                    "itemSubName_jp": "正品ティップ確認可能<br>オリジナル・プレミアムレーザーリフティング",
                    "itemName_th": "อัลเทอร่า 300 ช็อต  + Premium ACU ฉีดลดแฟต 9cc",
                    "itemSubName_th": "เลเซอร์ยกกระชับแบบพรีเมี่ยม<br>ผลิตภัณฑ์แท้ แกะกล่องใหม่เฉพาะตอนใช้เท่านั้น สามารถตรวจสอบก่อนเข้ารับบริการได้",
                    "itemName_vn": "Ulthera Chính hãng  300 shots",
                    "itemSubName_vn": " Có thể xác nhận kim chính hãng <br> Lifting Laser Premium  nguyên gốc ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "41",
                    "mainName": "울쎄라리프팅"
                },
                {
                    "id": "468",
                    "groupId": "17",
                    "middleId": "54",
                    "originalPrice": "290000",
                    "discountedPrice": "190000",
                    "itemName": "벨로테로 필러 1cc",
                    "itemSubName": "목, 눈가, 입가, 마리오네트<br>미세주름필러",
                    "itemName_eng": "Belotero Filler 1cc",
                    "itemSubName_eng": "Fine Lines Wrinkles Filler - <br> ",
                    "itemName_jp": "ベロテロフィラー1㏄",
                    "itemSubName_jp": "微細シワフィラー　首、目元、口角、マリオネット",
                    "itemName_th": "ฟิลเลอร์ยี่ห้อ Belotero 1cc",
                    "itemSubName_th": "ฟิลเลอร์ลดริ้วรอยที่เป็นเส้นๆ<br> ",
                    "itemName_vn": "Filler  Belotero 1cc",
                    "itemSubName_vn": "cổ , bờ mắt,  khóe miệng,  mép<br>Filler làm giảm nếp nhăn nhỏ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "13",
                    "mainName": "얼굴필러"
                },
                {
                    "id": "4593",
                    "groupId": "17",
                    "middleId": "112",
                    "originalPrice": "190000",
                    "discountedPrice": "99000",
                    "itemName": "듀엣RF 리프팅 200샷",
                    "itemSubName": "잔주름 개선 고주파 리프팅",
                    "itemName_eng": "Duet RF Lifting 200 shots",
                    "itemSubName_eng": "Fine lines improving High frequency Lifting",
                    "itemName_jp": "デュエットRFリフティング200ショット",
                    "itemSubName_jp": "小じわ改善&高周波リフティング",
                    "itemName_th": "ดูเอต RF ลิฟทิ่ง 200 ช็อต",
                    "itemSubName_th": "ช่วยยกกระชับผิว ลดเลือนริ้วรอย",
                    "itemName_vn": "Duet RF Lifting 200 shots",
                    "itemSubName_vn": "Lifting tần số cao cải thiện nếp nhăn nhỏ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "41",
                    "mainName": "듀엣써마지"
                },
                {
                    "id": "508",
                    "groupId": "17",
                    "middleId": "623",
                    "originalPrice": "100000",
                    "discountedPrice": "69000",
                    "itemName": "트리플바디 1회",
                    "itemSubName": "붓기제거 / 혈액순환 <br>/ 셀룰라이트 해결!",
                    "itemName_eng": "Triple Body 1 session",
                    "itemSubName_eng": "Blood Circulation / Swelling / Facilitate Fat Digestion<br>Swelling Legs,<br>Cellulite that You Feel Every Time You Touch<br>Solve it with Circulation!",
                    "itemName_jp": "トリプルボディー1回",
                    "itemSubName_jp": "血液循環・むくみ・脂肪分解促進<br>腫れた足、<br>触るたびに感じられるセルライト<br>循環で解決！",
                    "itemName_th": "ทริปเปิ้ลบอดี้ 1 ครั้ง",
                    "itemSubName_th": "ช่วยสลายไขมันส่วนเกินที่รบกวนใจ<br>ปัญหาขาใหญ่<br>และช่วยในกระตุ้นการไหลเวียนของเลือดได้ดีขึ้น<br>ลดอาการแขนขาบวม",
                    "itemName_vn": "Triple Body 1  lần",
                    "itemSubName_vn": " Loại bỏ sưng /  Tuần hoàn  máu <br>/  Giải quyết cellulite!",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "30",
                    "mainName": "트리플바디"
                },
                {
                    "id": "4056",
                    "groupId": "17",
                    "middleId": "3207",
                    "originalPrice": "40000",
                    "discountedPrice": "22000",
                    "itemName": "핑크팻주사 10cc",
                    "itemSubName": "지방분해 / 셀룰라이트감소 <br>원하는 국소부위까지 세밀하게 가능<br>적은용량으로 붓기최소화",
                    "itemName_eng": "Pink Fat Injection 10 cc ",
                    "itemSubName_eng": "Fat Digestion / Cellulite Reduction <br> Detailed Treatment at Desired Areas",
                    "itemName_jp": "ピンクファット注射10㏄",
                    "itemSubName_jp": "脂肪分解 / セルライト減少 <br>望む局所部位まで細かく可能！<br>少ない量で腫れを最小化",
                    "itemName_th": "ฉีดพิ้งค์แฟต 10cc",
                    "itemSubName_th": "กำจัดไขมันและเซลลูไลท์ <br>สามารถฉีดเพื่อลดเฉพาะจุดที่ต้องการได้ทุกซอกทุกมุม",
                    "itemName_vn": " Tiêm Pink Fat I 10 cc ",
                    "itemSubName_vn": "Phân hủy mỡ /  Giảm Cellulite<br>Tỉ mỉ đến từng bộ phận mong muốn<br> Giảm thiếu sưng với liều lượng nhỏ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "30",
                    "mainName": "핑크팻주사"
                },
                {
                    "id": "3878",
                    "groupId": "17",
                    "middleId": "110",
                    "originalPrice": "280000",
                    "discountedPrice": "159000",
                    "itemName": "시너지 MPX 나비존 3회<br>(안면홍조, 붉은흉터)<br>+ 초크초크마스크 3회",
                    "itemSubName": "콜라겐 재생 / 안면홍조<br>여드름 붉은흉터 개선",
                    "itemName_eng": "Cynergy MPX Butterfly Zone (Facial flush, Redness Scars) 3 times<br>+ CHOK CHOK mask 3 sessions",
                    "itemSubName_eng": "Collagen regeneration / Facial flush<br>Improve acne redness scars",
                    "itemName_jp": "シナジーMPXバタフライゾーン（赤み、赤いあと）3回 <br>+ チョクチョクマスクパック3枚",
                    "itemSubName_jp": "コラーゲン再生 / 赤み<br>ニキビ　赤い跡改善",
                    "itemName_th": "เลเซอร์ลดรอยแดง [Cynergy MPX] บริเวณแก้มและจมูก 3 ครั้ง + มาส์ก CHOK CHOK 3 ครั้ง",
                    "itemSubName_th": "ผลิตคอลลาเจนใหม่ / ลดความแดงของใบหน้า<br>หรือรอยแดงจากสิว",
                    "itemName_vn": "Cynergy MPX vùng nabi  3 lần <br>(mặt đỏ, sẹo đỏ)<br>+ mặt nạ Chok Chok  3 lần",
                    "itemSubName_vn": "Tái tạo collagen / mặt đỏ br>cải thiện sẹo đỏ do mụn",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "27",
                    "mainName": "홍조레이저[시너지MPX]"
                },
                {
                    "id": "1849",
                    "groupId": "17",
                    "middleId": "2623",
                    "originalPrice": "190000",
                    "discountedPrice": "119000",
                    "itemName": "시크릿레이저 1회",
                    "itemSubName": "RF고주파니들 / 피부 탄력 강화 <br>/ 모공축소 / 피부재생 <br>/ 여드름 흉터 개선<br><br>*1회용 팁값별도 +5만원",
                    "itemName_eng": "Secret Laser 1 session",
                    "itemSubName_eng": "RF High Frequency Needle / Improve Skin Elasticity  / Pore Minimizing / Skin Regeneration<br> / Improve acne scars<br>*Individual Single-use Tip ₩50,000",
                    "itemName_jp": "シークレットレーザー1回",
                    "itemSubName_jp": "RF高周波ニードル、肌の弾力強化、毛穴縮小、肌再生 <br>/ ニキビ跡改善<br>*一回用ティップ(専用針)費用別5.5万ウォン",
                    "itemName_th": "ซีเคร็ตเลเซอร์ 1 ครั้ง",
                    "itemSubName_th": "เลเซอร์ด้วยเข็ม RF/ ช่วยให้ผิวยืดหยุ่นได้อย่างแข็งแรง/  ยกกระชับรูขุมขน/ ฟื้นฟูสภาพผิว<br> ลดเลือนรอยสิว<br>*ทั้งนี้ไม่รวมค่าเปลี่ยนเข็มเพิ่ม ครั้งละ 50,000 วอน",
                    "itemName_vn": "Secret Laser 1 lần",
                    "itemSubName_vn": "Kim tần số cao RF / Tăng độ đàn hồi da <br>/  Thu nhỏ lỗ chân lông /  Tái tạo da <br>/  Cải thiện sẹo mụn<br>* Chưa bao gồm giá kim 1 lần dùng    50.000 won ",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "시크릿레이저"
                },
                {
                    "id": "3879",
                    "groupId": "17",
                    "middleId": "2623",
                    "originalPrice": "360000",
                    "discountedPrice": "199000",
                    "itemName": "시크릿레이저 + 아기주사",
                    "itemSubName": "RF고주파니들<br>콜라겐재생, 모공축소, 피지감소<br><br>*1회용 팁값별도 +5만원",
                    "itemName_eng": "Secret + Baby face Injection",
                    "itemSubName_eng": "RF High Frequency Needle / Collagen Regeneration , Pore Minimizing , Sebum Reduction<br>*Individual Single-use Tip ₩50,000",
                    "itemName_jp": "シークレットレーザー＋ベビー注射",
                    "itemSubName_jp": "RF高周波ニードル、コラーゲン再生、毛穴縮小、皮脂減少<br>*一回用ティップ(専用針)費用別5.5万ウォン",
                    "itemName_th": "ซีเคร็ตเลเซอร์  + ฉีด Baby Face",
                    "itemSubName_th": "เลเซอร์ด้วยเข็ม RF/ ช่วยให้ผิวยืดหยุ่นได้อย่างแข็งแรง/  ยกกระชับรูขุมขน/ ฟื้นฟูสภาพผิว<br> ลดเลือนรอยสิว<br>*ทั้งนี้ไม่รวมค่าเปลี่ยนเข็มเพิ่ม ครั้งละ 50,000 วอน",
                    "itemName_vn": "Secret + Tiêm Baby face ",
                    "itemSubName_vn": "Kim tần số cao RF <br>Tái tạo collagen, Thu nhỏ lỗ chân lông , Giảm bã nhờn <br>* Chưa bao gồm giá kim một lần dùng   50.000won",
                    "cha": "17",
                    "cha_2": "17",
                    "cha_0": "0",
                    "categoryId": "26",
                    "mainName": "시크릿레이저"
                }
            ]
        },
        {
            "id": "622",
            "chainId": "1",
            "middleId": null,
            "groupName": "물광뿜뿜 피부주사 EVENT",
            "groupSubName": "[피부주사 EVENT] 평일, 주말 상관없이 올타임 적용!",
            "dayOfTheWeek": "123456",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "4",
            "regDate": "2019-09-25 12:25:03",
            "selected": "1",
            "selected_list": "0",
            "startDate_list": null,
            "endDate_list": null,
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "6",
            "orderby_0": "0",
            "print_orderby_1": "0",
            "print_orderby_2": "0",
            "createAdminId": "ggghhh27",
            "lastUpdateAdminId": null,
            "groupName_eng": "",
            "groupSubName_eng": "",
            "groupName_jp": "水光肌、皮膚注射EVENT",
            "groupSubName_jp": "[皮膚注射 EVENT] 平日,週末関係なくオールタイム適応！",
            "groupName_th": "โปรโมชั่นฉีดหน้าใส",
            "groupSubName_th": "[โปรโมชั่นฉีดหน้าใส] โปรวันธรรมดาและวันเสาร์ ตลอดทั้งวัน",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,jp,th",
            "groupName_vn": "",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "7047",
                    "groupId": "622",
                    "middleId": "59",
                    "originalPrice": "140000",
                    "discountedPrice": "89000",
                    "itemName": "물광톡스",
                    "itemSubName": "물광주사 2cc + 더모톡신",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "水光トクス",
                    "itemSubName_jp": "水光注射2cc+ドマトクシン",
                    "itemName_th": "เซตหน้าฉ่ำ + ไร้ริ้วรอย",
                    "itemSubName_th": "ฉีดหน้าฉ่ำวาว + โบท็อกซ์ลิฟท์หน้า",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "622",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "물광주사"
                },
                {
                    "id": "7048",
                    "groupId": "622",
                    "middleId": "60",
                    "originalPrice": "160000",
                    "discountedPrice": "109000",
                    "itemName": "연어톡스",
                    "itemSubName": "연어주사 + 더모톡신",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "サーモントクス",
                    "itemSubName_jp": "サーモン注射+ドマトクシン",
                    "itemName_th": "เซตหน้าใสด้วย DNA ปลาแซลมอน",
                    "itemSubName_th": "ฉีดแคลซิโทนิน + โบท็อกซ์ลิฟท์หน้า",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "622",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "피부재생 주사"
                },
                {
                    "id": "7049",
                    "groupId": "622",
                    "middleId": "60",
                    "originalPrice": "400000",
                    "discountedPrice": "219000",
                    "itemName": "리쥬톡스",
                    "itemSubName": "리쥬란힐러 + 더모톡신",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "リジュトクス",
                    "itemSubName_jp": "リジュランヒーラー+ドマトクシン",
                    "itemName_th": "เซต Rejuran + หน้าเด้ง",
                    "itemSubName_th": "็ฉีด Rejuran Healer + โบท็อกซ์ลิฟท์หน้า",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "622",
                    "cha_2": "0",
                    "cha_0": "0",
                    "categoryId": "43",
                    "mainName": "피부재생 주사"
                }
            ]
        },
        {
            "id": "555",
            "chainId": "1",
            "middleId": null,
            "groupName": "실리프팅 EVENT",
            "groupSubName": "[실리프팅 EVENT] 평일, 주말 상관없이 올타임 적용!",
            "dayOfTheWeek": "123456",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "5",
            "regDate": "2019-07-25 16:23:41",
            "selected": "1",
            "selected_list": "0",
            "startDate_list": null,
            "endDate_list": null,
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "7",
            "orderby_0": "0",
            "print_orderby_1": "5",
            "print_orderby_2": "6",
            "createAdminId": "ggghhh27",
            "lastUpdateAdminId": null,
            "groupName_eng": "",
            "groupSubName_eng": "",
            "groupName_jp": "糸リフトイベント",
            "groupSubName_jp": "",
            "groupName_th": "โปรโมชั่นร้อยไหม",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,jp,th,vn",
            "groupName_vn": "Khuyến mãi dịch vụ căng da mặt bằng chỉ",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "4380",
                    "groupId": "555",
                    "middleId": "56",
                    "originalPrice": "400000",
                    "discountedPrice": "250000",
                    "itemName": "민트 4줄(턱라인) <br>+ 타이트닝 주사",
                    "itemSubName": "360도 돌기가 있는 4세대 리프팅",
                    "itemName_eng": "Mint 4 threads (Jawline) + Tightening Injection",
                    "itemSubName_eng": "4th generation lifting with 360 degrees turn",
                    "itemName_jp": "ミント4本（あごライン）<br>+タイトニング注射",
                    "itemSubName_jp": "360度突起がある4世代リフティング",
                    "itemName_th": "ร้อยไหมมินต์ 4 เส้น (บริเวณสันกราม) + ฉีด Tightening ",
                    "itemSubName_th": "ยกกระชับแบบ 360 องศา",
                    "itemName_vn": "Mint  4 sợi(Khuôn cằm) <br>+ Tiêm tightening",
                    "itemSubName_vn": " Lifting thế hệ 4  quay 360 độ",
                    "cha": "555",
                    "cha_2": "555",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "실리프팅"
                },
                {
                    "id": "3432",
                    "groupId": "555",
                    "middleId": "56",
                    "originalPrice": "790000",
                    "discountedPrice": "550000",
                    "itemName": "민트 4줄 <br>+ 블루다이아 4줄",
                    "itemSubName": "처진 앞볼과 턱라인을<br>효과적으로 UP!",
                    "itemName_eng": "Jawline + Smile lines Lifting<br>Minet 4 threads + Blue Dia 4 threads",
                    "itemSubName_eng": "Effectively Lift UP the Sagged Cheeks and Jawline!",
                    "itemName_jp": "あごライン＋ほうれい線リフト <br>ミント4本＋ブルーダイヤ4本",
                    "itemSubName_jp": "たるんだ頬とあごラインを効果的にUP!",
                    "itemName_th": "ร้อยไหมมินต์ 4 เส้น (บริเวณกราม) <br>+ ไหมบลูโรส 4 เส้น (ร่องแก้ม)",
                    "itemSubName_th": "ยกกระชับร่องแก้มและกรามอย่างเต็มประสิทธิภาพ",
                    "itemName_vn": "Mint 4sợi <br>+ Blue Dia 4 sợi",
                    "itemSubName_vn": "Khuôn cằm và gò má chảy xệ<br>Hiệu quả UP!",
                    "cha": "555",
                    "cha_2": "555",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "실리프팅"
                },
                {
                    "id": "5373",
                    "groupId": "555",
                    "middleId": "56",
                    "originalPrice": "970000",
                    "discountedPrice": "620000",
                    "itemName": "민트 6줄(턱라인)<br>+ 블루다이아 4줄",
                    "itemSubName": "처진 앞볼과 턱라인을<br>효과적으로 UP!",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "ミント6本（あごライン）<br>+ブルーダイヤ4本",
                    "itemSubName_jp": "たるんだ頬とあごラインを効果的にUP!",
                    "itemName_th": "ร้อยไหมมินต์ 6 เส้น (บริเวณกราม)<br> + ร้อยไหมบลูโรส 4 เส้น(ร่องแก้ม)",
                    "itemSubName_th": "ร้อยไหมบริเวณกรามทั้งสองข้าง<br>ให้กระชับและเรียวสวย",
                    "itemName_vn": "Mint  6 sợi (Khuôn hàm)<br>+ Blue Dia 4 sợi",
                    "itemSubName_vn": " Khuôn hàm và má chảy xệ<br>hiệu quả tăng  UP!",
                    "cha": "555",
                    "cha_2": "555",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "실리프팅"
                },
                {
                    "id": "3041",
                    "groupId": "0",
                    "middleId": "56",
                    "originalPrice": "440000",
                    "discountedPrice": "320000",
                    "itemName": "팔자리프팅 <br>블루다이아 4줄",
                    "itemSubName": "처진앞볼, 팔자부위 탄력 UP!",
                    "itemName_eng": "Smile Lines Lifting <br> Blue Dia 4 threads",
                    "itemSubName_eng": "Sagged cheeks, Smile lines areas elasticity UP",
                    "itemName_jp": "ほうれい線リフト <br>ブルーダイヤ4本",
                    "itemSubName_jp": "たるんだ頬、ほうれい線の弾力UP",
                    "itemName_th": "ร้อยไหมร่องแก้ม <br>ร้อยไหมบลูโรส 4 เส้น",
                    "itemSubName_th": "อัพร่องแก้มที่ห้อยและหย่อนคล้อยให้กระชับมากขึ้น!",
                    "itemName_vn": " Lifting rãnh má <br>Blue Dia 4 sợi",
                    "itemSubName_vn": " Độ đàn hồi rãnh má, má chảy xệ UP!",
                    "cha": "555",
                    "cha_2": "555",
                    "cha_0": "0",
                    "categoryId": "86",
                    "mainName": "실리프팅"
                }
            ]
        },
        {
            "id": "42",
            "chainId": "1",
            "middleId": null,
            "groupName": "패키지 EVENT",
            "groupSubName": "[패키지 EVENT] 평일, 주말 상관없이 올타임 적용!",
            "dayOfTheWeek": "123456",
            "startDate": null,
            "endDate": null,
            "startTime": "10",
            "endTime": "20",
            "orderby": "6",
            "regDate": "2018-02-28 15:31:23",
            "selected": "1",
            "selected_list": "0",
            "startDate_list": null,
            "endDate_list": null,
            "isShow": "1",
            "isShow_2": "1",
            "isShow_0": "1",
            "orderby_2": "8",
            "orderby_0": "8",
            "print_orderby_1": "7",
            "print_orderby_2": "8",
            "createAdminId": null,
            "lastUpdateAdminId": null,
            "groupName_eng": "Skin Care Package",
            "groupSubName_eng": "",
            "groupName_jp": "パッケージイベント",
            "groupSubName_jp": "",
            "groupName_th": "ทรีทเม้นท์ แพ็กเกจ",
            "groupSubName_th": "",
            "sns": "0",
            "groupName_gd": "",
            "groupSubName_gd": "",
            "country": "kor,eng,jp,th,vn",
            "groupName_vn": "Khuyến mãi gói",
            "groupSubName_vn": "",
            "items": [
                {
                    "id": "3725",
                    "groupId": "42",
                    "middleId": "3160",
                    "originalPrice": "750000",
                    "discountedPrice": "459000",
                    "itemName": "프리미엄<br>피코 화이트닝 패키지",
                    "itemSubName": "프리미엄 토닝레이저",
                    "itemName_eng": "Premium Pico Whitening Package",
                    "itemSubName_eng": "Premium Toning Laser",
                    "itemName_jp": " プレミアム・ピコホワイトニングパッケージ",
                    "itemSubName_jp": "プレミアムトーニングレーザー<br>1週目:ピコトーニング+ピコズームパスくすみ除去モード（名刺サイズ）+ ldm水玉レーザー<br>2週目:デュアルトーニング+酸素ピール+再生管理<br>3週目:ピコトーニング+ゴールドテラピー<br>4週目:デュアルトーニング+プレミアム美白管理<br>5週目:ピコトーニング+ピコズームパスくすみ除去モード（名刺サイズ）+再生管理<br>6週目:デュアルトーニング+ハニープロポリス管理",
                    "itemName_th": "แพ็กเกจ พรีเมี่ยม พิโค ไวท์เทนนิ่ง 6  สัปดาห์",
                    "itemSubName_th": "พรีเมี่ยม โทนนิ่งเลเซอร์",
                    "itemName_vn": " Gói làm trắng da Pico Premium",
                    "itemSubName_vn": "Premium Toning Laser",
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": "27",
                    "mainName": "피코슈어 레이저토닝"
                },
                {
                    "id": "8327",
                    "groupId": "0",
                    "middleId": "2732",
                    "originalPrice": "400000",
                    "discountedPrice": "219000",
                    "itemName": "레이저, 주사NONO<br>수분 미백 올인원 패키지",
                    "itemSubName": "1주 | 물톡스  +LDM 8분 + LED 광선<br>+ 벨벳마스크<br>\n2주 | 오투덤산소테라피 + 크라이오<br>(수분) + LED광선 + 모델링<br>\n3주 | 로즈필 + 로즈솔루션러빙<br>+ 크라이오(미백) + 로즈마스크<br>+ 모델링<br>\n4주 | 그린필 + LDM 8분<br>+ 화이트마스크팩 + 모델링",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "レーザー、注射NONO<br>水分美白オールインワンパッケージ",
                    "itemSubName_jp": "1週間|水トックス+ LDM+ LED光線<br>+ベルベットマスク<br>2週間|O2ダーム酸素テラピー+再生管理+モデリング<br>3週間|ローズピール+プレミアム美白管理+ LED光線+モデリング<br>4週間|グリンピール+ LDM+ LED光線<br>+モデリング",
                    "itemName_th": "แพ็กเกจ ทรีทเม้นท์หน้าใส  4 สัปดาห์<br>เพิ่มความชุ่มชื้น + หน้าขาวใสขึ้น",
                    "itemSubName_th": "สัปดาห์ที่ 1 วอเตอร์ ดรอป พิลลิ่ง + LDM <br>+ มาส์กแสง LED + มาส์ก Velvet<br>สัปดาห์ที่ 2 O2 to Derm ออกซิเจน เธอราพี <br>+ ทรีทเม้นท์ฟื้นฟูผิว + โมเดลลิ่งมาส์ก<br>สัปดาห์ที่ 3 โรสพิล + พรีเมี่ยม วิตามิน ไวท์เทนนิ่งแคร์<br>+ มาส์กแสง LED + โมเดลลิ่งมาส์ก<br>สัปดาหที่ 4 กรีนพิล + LDM + มาส์กแสง LED + โมเดลลิ่งมาส์ก",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": "42",
                    "mainName": "물톡스"
                },
                {
                    "id": "7222",
                    "groupId": "42",
                    "middleId": "3160",
                    "originalPrice": "1350000",
                    "discountedPrice": "699000",
                    "itemName": "[NEW!] 프리미엄<br>피코 올인원 화이트닝 패키지",
                    "itemSubName": "미백, 잡티, 콜라겐까지!<br>올인원집중패키지",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "【NEW！】プレミアム<br>ピコオールインワンホワイトニングパッケージ",
                    "itemSubName_jp": "美白、くすみ、コラーゲンまで！<br>オールインワン集中パッケージ<br>1週目:ピコトーニング+ LDM水玉レーザー <br>2週目:シナジートーニング+酸素ピール+再生管理 <br>3週目:ピコトーニング+ゴールドセラピー <br>4週目:シナジートーニング+プレミアム美白管理 <br>5週目:ピコトーニング+ピコズームパスくすみ除去モード（名刺サイズ）+再生管理 <br>6週目:シナジートーニング+水トックス <br>7週目:ピコトーニング+ LDM水玉レーザー <br>8週目:シナジートーニング+O2Derm酸素テラピー <br>9週目:ピコトーニング+ピコズームパスくすみ除去モード（名刺サイズ）+再生管理 <br>10週目:シナジートーニング+ハニープロポリス",
                    "itemName_th": "[NEW!]  All  in one<br>พรีเมี่ยม พิโค ไวท์เทนนิ่ง",
                    "itemSubName_th": "แพ็กเกจ เลเซอร์ลดฝ้า กระ จุดด่างดำ<br>แบบ 10 สัปดาห์",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": "27",
                    "mainName": "피코슈어 레이저토닝"
                },
                {
                    "id": "8186",
                    "groupId": "42",
                    "middleId": "3350",
                    "originalPrice": "800000",
                    "discountedPrice": "420000",
                    "itemName": "여드름 4주 한달 순삭 패키지",
                    "itemSubName": "*원장님 상담후 여드름 약 처방 <br><br>1주 | 아쿠아필+PDT<br>+전체압출+염증주사<br>( 모공청소 살균 피지감소)<br>2주 | 카프리레이저+LDM(베이직)<br>+전체압출+염증주사<br>(피지조절 염증완화 피부재생)<br>3주 | 카프리레이저+재생관리<br>+전체압출+염증주사<br>(피지조절 염증완화 모공청소 살균)<br>4주 | 알라딘필+전체 압출+염증주사<br>( 여드름 색소침착재생, 피부결 개선)<br>",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "ニキビ４週１か月ですっきりパッケージ",
                    "itemSubName_jp": "*院長と相談後ニキビ薬処方<br><br>1週 | アクアピール+PDT<br>+全体圧出+炎症注射<br>( 毛穴掃除 殺菌 皮脂減少)<br>2週 | カプリレーザー+LDM(ベーシック)<br>+全体圧出+炎症注射<br>(皮脂調節 炎症緩和 皮膚再生)<br>3週| カプリレーザー+再生管理<br>+全体圧出+炎症注射<br>(皮脂調節 炎症緩和 毛穴掃除 殺菌)<br>4週| アラジンピール+全体圧出+炎症注射<br>( ニキビ 色素沈着再生, 皮膚のキメ改善)<br>",
                    "itemName_th": "แพ็กเกจรักษาสิวภายใน 4 สัปดาห์",
                    "itemSubName_th": "ใบสั่งยารักษาสิวจะได้หลังจากเข้ารับคำปรึกษากับแพทย์แล้ว<br><br>สัปดาห์ที่ 1 | อควาพิล+PDT<br>+กดสิว+ฉีดสิวอักเสบ<br>( ทำความสะอาดผิวหน้าเบื้องต้น)<br>สัปดาห์ที่ 2 | Capri Laser+LDM(เบสิคแคร์)<br>+กดสิว+ฉีดสิวอักเสบ<br>(ลดความมัน ลดสิวอักเสบและสิวอุดตัน)<br>สัปดาห์ที่ 3 | Capri Laser+LDM(เบสิคแคร์)<br>+กดสิว+ฉีดสิวอักเสบ<br>(ลดความมัน ลดสิวอักเสบ ฟื้นฟูสภาพผิว)<br>สัปดาห์ที่ 4 | อะลาดินพิล + กดสิว + ฉีดสิวอักเสบ<br>(ผลัดเซลล์ผิวให้รอยสิวจางลง)",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "여드름패키지 (5주/7주) 사용중"
                },
                {
                    "id": "5620",
                    "groupId": "42",
                    "middleId": "3350",
                    "originalPrice": "1300000",
                    "discountedPrice": "690000",
                    "itemName": "여드름 타파 7주 패키지",
                    "itemSubName": "*원장님 상담후 여드름 약 처방 ",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "【NEW！】<br>にきび打破7週パッケージ",
                    "itemSubName_jp": "*院長相談後、にきびの薬処方",
                    "itemName_th": "แพ็กเกจกำจัดสิว 7 สัปดาห์",
                    "itemSubName_th": "*สามารถสั่งยารักษาสิวได้หลังจากเข้ารับคำปรึกษากับแพทย์ผู้เชี่ยวชาญแล้ว",
                    "itemName_vn": "[NEW!]<br> Gói trị mụn 7 tuần ",
                    "itemSubName_vn": "* Kê đơn thuốc sau khi tư vấn với viện trưởng",
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "여드름패키지 (5주/7주) 사용중"
                },
                {
                    "id": "2521",
                    "groupId": "42",
                    "middleId": "2797",
                    "originalPrice": "870000",
                    "discountedPrice": "450000",
                    "itemName": "아기모공 5주 패키지",
                    "itemSubName": "넓어진 모공 축소, 흉터개선<br>재생관리 패키지!",
                    "itemName_eng": "Baby Pores 5-week Package",
                    "itemSubName_eng": "Broadened Pores Minimizing, Improve Scars<br>Skin Regeneration Treatment all at Once!",
                    "itemName_jp": "赤ちゃん毛穴5週パッケージ",
                    "itemSubName_jp": "広がった毛穴縮小、あと改善<br>再生管理を一気に！<br>1週目:アクアピール+ PDT<br>2週目:シークレットレーザー+赤ちゃん注射<br>3週目:ジェネシス+ Vモチモチテラピー<br>4週目:スペクトラピール+再生管理<br>5週目:フラクセルレーザー+毛穴注射",
                    "itemName_th": "แพ็กเกจบอกลารูขุมขนกว้าง 5 สัปดาห์",
                    "itemSubName_th": "ช่วยยกกระชับรูขุมขน, แก้ไขรอยแผลเป็นจากสิว<br>และฟื้นฟูสภาพผิวให้แข็งแรงขึ้นภายในขั้นตอนเดียว!",
                    "itemName_vn": "Gói lỗ chân lông baby 5 tuần ",
                    "itemSubName_vn": "Thu nhỏ lỗ chân lông,  cải thiện sẹo<br> gói chăm sóc tái tạo da!",
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "아기모공 5주 패키지"
                },
                {
                    "id": "489",
                    "groupId": "42",
                    "middleId": "637",
                    "originalPrice": "550000",
                    "discountedPrice": "290000",
                    "itemName": "속살 쏙쏙 속성 3주 패키지",
                    "itemSubName": "단기 속성 체형관리!<br>*원장님 상담 후 비만약 처방<br><br>1주 | 메가스키니4000샷 <br>+ 걸그룹주사 200cc <br>2주 | 트리플바디 <br>+ 걸그룹주사 200cc <br>3주 | 메가스키니 4000샷 <br>+ 걸그룹주사200cc",
                    "itemName_eng": "Hidden Fat Simple 3-week Package",
                    "itemSubName_eng": "Short & Quick Body shape Management!",
                    "itemName_jp": "お肉すっきり3週パッケージ",
                    "itemSubName_jp": "短期即効ボディーライン管理！<br> ＊院長の相談後､肥満薬処方<br><br> <b>1週間</b>|メガスキニー4000ショット<br>+ガールズグループの注射200CC<br> <b>2週間</b>|トリプルボディー<br>+ガールズグループの注射200CC<br> <b>3週間</b>|メガスキニー4000ショット<br>+ガールズグループ注射200CC",
                    "itemName_th": "แพ็กเกจบอดี้ไลน์ 3 สัปดาห์",
                    "itemSubName_th": "หุ่นสวยเพรียวได้ภายใน 3 สัปดาห์!",
                    "itemName_vn": "Gói giảm mỡ  sâu bên trong nhanh chóng 3 tuần ",
                    "itemSubName_vn": " Quản lý hình thể nhanh chóng trong thời gian ngắn!<br>* Tư vấn với viện trưởng sau đó kê đơn thuốc giảm béo",
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "속살 쏙쏙 속성 3주 패키지 (8월1차~)"
                },
                {
                    "id": "7835",
                    "groupId": "42",
                    "middleId": "637",
                    "originalPrice": "800000",
                    "discountedPrice": "450000",
                    "itemName": "속살 쏙쏙 6주패키지",
                    "itemSubName": "*원장님 상담후 비만약 처방<br><br>1주 | 바디보톡스 150U<br>+ 핑크팻 80cc<br>2주 | 트리플바디 + 핑크팻 40cc<br>+ 걸그룹 200cc<br>3주 | 울핏 400샷 + 핑크팻 80cc<br>4주 | 메가스키니 5000샷<br>+ 핑크팻 40cc +걸그룹 200cc<br>5주 | 트리플 바디 + 핑크팻 80cc<br>6주 | 메가스키니 5000샷<br>+핑크팻 80cc",
                    "itemName_eng": "",
                    "itemSubName_eng": "",
                    "itemName_jp": "お肉すっきり6週パッケージ",
                    "itemSubName_jp": "*院長の相談後肥満薬処方<br><br>1週間 | ボディボトックス150U<br>+ ピンクファット80cc<br>2週間|トリプルボディ + ピンクファット40cc<br>+ ガールグループ200cc<br>3週間 | ウルフィット400ショット+ピンクファット80cc<br>4週間 | メガスキニー5000ショット<br>+ピンクファット40cc+ガールグループ 200cc<br>5週 |トリプルボディ+ ピンクファット80cc<br>6週間 | メガスキニー5000ショット<br>+ピンクファット 80cc",
                    "itemName_th": "แพ็กเกจ บอดี้ไลน์ 6 สัปดาห์",
                    "itemSubName_th": "สัปดาห์ที่ 1  : บอดี้โบท็อกซ์ 150 ยูนิต<br>+ พิงค์แฟต 80cc<br>สัปดาห์ที่ 2  : ทริปเบิ้ลบอดี้ + พิงค์แฟต 40cc<br>+ เกิร์ลกรุ๊ป 200cc<br>สัปดาห์ที่ 3 : อูฟิต 400 ช็อต<br>+ พิงค์แฟต 80cc<br>สัปดาห์ที่ 4 : เมกาสกินนี่ 5000 ช็อต + พิงค์แฟต 40cc<br>+ เกิร์ลกรุ๊ป 200cc<br>สัปดาห์ที่ 5 : ทริปเบิ้ลบอดี้<br>+ พิงค์แฟต 80cc<br>สัปดาห์ที่ 6 : เมกาสกินนี่ 5000 ช็อต<br>+ พิงค์แฟต 80cc",
                    "itemName_vn": null,
                    "itemSubName_vn": null,
                    "cha": "42",
                    "cha_2": "42",
                    "cha_0": "0",
                    "categoryId": null,
                    "mainName": "속살 쏙쏙 속성 3주 패키지 (8월1차~)"
                }
            ]
        }
    ],
    "banner": {
        "chainId": "1",
        "chaName": "3월 1차 이벤트",
        "startDate": "2020-03-01",
        "endDate": "2020-03-15",
        "isTab": "0",
        "regDate": "2018-02-12 15:11:41",
        "showDate": "2018-05-30",
        "cha": "1",
        "imgcheck": "0",
        "chaName_jp": "3月1次 イベント",
        "chaName_th": "โปรโมชั่นครึ่งแรกของเดือนกุมภาพันธ์",
        "chaName_gd": "3月上半月活动",
        "chaName_eng": "March 1st",
        "chaName_vn": "Khuyến mãi tháng 1 lần 1"
    }
}